name: Test workflow
on: 
 push:
    branches:
    - main
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
         - name: step1
           run: echo "This is a test"
         - name: step2
           uses: actions/checkout@v3
         - name: step3
           run: mvn -B compile
       
  
